wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710768829.224877
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
