wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710645476.179281
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.8
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
gen_lr:
  desc: null
  value: 0.0001
dis_lr:
  desc: null
  value: 0.0001
CD_lr:
  desc: null
  value: 1.0e-05
CD_type:
  desc: null
  value: MLP
G_type:
  desc: null
  value: TCN
D_type:
  desc: null
  value: TCN
Gamma:
  desc: null
  value: 5.0
